#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Welcome!'
dotnet husky run --name welcome


branch_name=$(git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3)

if [ "branch" = "master" ]; then
  echo "You can't push directly to master branch."
  exit 1
fi

echo 'Prepare Release'
dotnet msbuild -bl -p:Configuration=Release -p:Deterministic=true src/NanoDbProfiler.AspNetCore/NanoDbProfiler.AspNetCore.csproj

echo "Package nuget"
dotnet pack ./src/NanoDbProfiler.AspNetCore/NanoDbProfiler.AspNetCore.csproj -o dist/ --no-build --configuration Release

echo 'Publish Release'
	dotnet nuget push "dist/NanoDbProfiler.AspNetCore.$(dotnet tool run nbgv get-version -v NuGetPackageVersion).nupkg" \
		--source https://www.myget.org/F/guneysu/api/v2/package --api-key=$MYGET_API_KEY

echo "Published Nuget Version:"
echo $(dotnet tool run nbgv get-version -v NuGetPackageVersion)
